# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HaloAILabs.HaloVoice
PackageVersion: 1.0.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
InstallerSuccessCodes:
- 3010
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.haloailabs.com/halovoice/Windows/Store/1.0.0/HaloVoiceSetup.exe
  InstallerSha256: 7EFAB3F9F9FD220F4B60D46FC739CD5907A0C6F737BE7F0A58860DC4B117723D
- Architecture: arm64
  MinimumOSVersion: 10.0.22000.0
  InstallerUrl: https://downloads.haloailabs.com/halovoice/Windows/Store/1.0.0/HaloVoiceSetup.exe
  InstallerSha256: 7EFAB3F9F9FD220F4B60D46FC739CD5907A0C6F737BE7F0A58860DC4B117723D
ManifestType: installer
ManifestVersion: 1.12.0
